- master/implnote.html
Address request in issue #10.
Using proper Aria attributes.
> Update Impl. note Figure 6.3.1 markup

- master/linking.html
Removed the out-dated xpointer references; added issue items for remaining questions.
> Linking Issues

- master/painting.html
> Clarify stroke-dasharray = 0

- master/struct.html
reordering, make a bit more rfc2119 (needs more), note localisation
mechanism is at risk since unimplemented
> tighten desc/title, note localisation at risk

- master/pservers.html
- master/types.html
> Make SVGUnitTypes a regular interface with only constants

- master/text.html
- master/types.html
Follow-up fix to #389. No change to changes section.
> Make DOMPointInit argument optional according to WebIDL spec.

- specs/integration/master/Overview.html
- specs/template/master/Overview.html
> Add GitHub link to Integration and Template

- master/definitions.xml
- master/geometry.html
- master/painting.html
- master/propidx.html
- master/shapes.html
- master/text.html
- master/types.html
Fixes #190.
Adds some minor reference clean up for number to remove hardcoded CSS2 references (number from CSS3 values is already in definitions.xml)
> Update <length> | <percentage> to <length-percentage>

- master/Overview.html
- master/access.html
- master/changes.html
- master/definitions.xml
- master/linking.html
- master/painting.html
- master/paths.html
- master/struct.html
- master/styling.html
- master/svgdom.html
- master/types.html
Also fixes a build break due to a missing < (yay XML!)
> Fix broken and missing references

- specs/animations/master/Overview.html
- specs/integration/master/Overview.html
- specs/paths/master/Overview.html
- specs/strokes/master/Overview.html
- specs/template/master/Overview.html
> Update http to https to avoid mixed content. Update http anchors while at it

- master/changes.html
- master/definitions.xml
- master/types.html
Follow https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-ispointinpath as much as it makes sense.
> Specify algorithm used for isPointInFill() and isPointInStroke(). #416

- master/painting.html
- specs/strokes/master/Overview.html
minor easthetic change
cc @dirkschulze @heycam
> Use stretchy parentheses for the arctan argument.

- master/definitions.xml
- master/styling.html
- master/text.html
These currently lack browser support.
Discussed in https://github.com/w3c/svgwg/issues/486
> Do not require text-align-all, text-space-collapse

- master/changes.html
- master/text.html
> Inline size: remove 'number' value.

- master/painting.html
- master/shapes.html
> Tag production rules with prod class

- master/pservers.html
Title of the paint servers chapter still mentioned SolidColor; removed
> remove dangling mention of SolidColor from chapter title

- master/changes.html
Tidying up the changes appendix. See commit messages for details.
Shouldn't really be any normative changes here, but I'd appreciate someone else taking a quick look to make sure I haven't broken anything.
I suspect that I'll find a few more missing changes as I go through the rest of the implementation review. But, it's still probably better to merge this sooner rather than later, so that other PRs (which all change the changes appendix, of course) can be rebased over top.
Other PRs will also need minor edits to add links to issues and PRs, as well as annotations to indicate that they are changes since the August CR, so that the tidy-up can last more than a few days!
> Clean-up Changes appendix

- specs/strokes/master/Overview.html
Fixes https://github.com/w3c/svgwg/issues/529
> Change stroke-width initial value to 1px

- master/changes.html
- master/conform.html
- master/coords.html
- master/embedded.html
- master/refs.html
- master/text.html
(Also some trailing whitespace removal)
> No need for XSL-FO, fixes issue 227

- master/access.html
- master/animate.html
- master/coords.html
- master/embedded.html
- master/geometry.html
- master/interact.html
- master/linking.html
- master/painting.html
- master/refs.html
- master/render.html
- master/styling.html
- master/types.html
- specs/animations/master/Overview.html
- specs/color/Overview.html
Update references to latest versions. Fixup inline references to undated forms, take account of great css renaming.
> Refs overhaul issue 514

- master/changes.html
- master/coords.html
- master/definitions.xml
- master/images/coords/ViewBox-Width150.svg
- master/images/coords/ViewBox.svg
- master/images/painting/vectorEffects/ve-fixedPosition.svg
- master/images/painting/vectorEffects/ve-initial.svg
- master/images/painting/vectorEffects/ve-nonRotation-fixedPosition.svg
- master/images/painting/vectorEffects/ve-nonRotation.svg
- master/images/painting/vectorEffects/ve-nonScalingSize-fixedPosition.svg
- master/images/painting/vectorEffects/ve-nonScalingSize-nonRotation-fixedPosition.svg
- master/images/painting/vectorEffects/ve-nonScalingSize-nonRotation.svg
- master/images/painting/vectorEffects/ve-nonScalingSize.svg
- master/images/painting/vectorEffects/ve-nonScalingStroke.svg
- master/images/painting/vectorEffects/ve-none.svg
- master/painting.html
- master/pservers.html
- master/shapes.html
- master/text.html
- master/types.html
Edits to fix https://github.com/w3c/svgwg/issues/519
> 519 kill local coords

- master/linking.html
Discovered in https://github.com/web-platform-tests/wpt/pull/13744.
> Fix Web IDL typo: PutsForwards -> PutForwards

- master/changes.html
> Fix type on 'Element' in changes section

- specs/animations/master/Overview.html
- specs/animations/master/definitions.xml
> Fix href in animation

- master/geometry.html
- master/propidx.html
Part 1, add geometry properties to prop index.
> Add CSS properties cx, cy, r, rx, ry, x, y to property index. #82

- master/changes.html
As @AmeliaBR noted this was missing
> add missing changes for DOMMatrix2DInit

- master/changes.html
- master/definitions.xml
Tested in https://github.com/web-platform-tests/wpt/pull/14876
resolves #627
> Mouse wheel event attribute is onwheel

- master/Overview.html
(same as used by CSS WG)
Links spec sections to associated tests, allows creation of test implementation report as needed to exit CR
> Add testing widget

- master/conform.html
> Typo fix: sofware -> software

- master/mimereg.html
> desk top => desktop

- master/linking.html
> Make it more clear what the difference is between URL and <url>

- master/style/expanders.js
- master/style/svg.css
This PR
- Makes show widget keyboard accessible
- Makes arrow icon decorative
closes https://github.com/w3c/svgwg/issues/110
> Make "show" widget in element definitions boxes play nicely with screen readers

- master/intro.html
Noticed that the "Relationship to previous" intro section had word missing in one sentence.  Also changed another word to improve the grammar slightly.
> Fixed missing word, and changed one

- master/linking.html
> Fix case of referrerpolicy="" attribute.

- master/coords.html
- master/painting.html
- master/shapes.html
- master/struct.html
- master/text.html
- master/types.html
- specs/animations/master/Overview.html
- specs/markers/master/Overview.html
- specs/paths/master/Overview.html
See https://github.com/heycam/webidl/pull/906.
> Replace void with undefined in Web IDL

- master/definitions.xml
Follow up to #840
spotted via https://github.com/w3c/webref/pull/187
> Add definition for CSSPseudoElement interface

- specs/animations/master/Overview.html
- specs/animations/master/definitions.xml
> Add `interfaces` for <discard> definition

- specs/svg-native/index.bs
> Minor typo

- master/embedded.html
> Fix typo in embedded.html

- master/coords.html
- master/definitions.xml
- master/embedded.html
- master/interact.html
- master/linking.html
- master/painting.html
- master/paths.html
- master/pservers.html
- master/shapes.html
- master/struct.html
- master/styling.html
- master/text.html
- master/types.html
- Mark certain factory functions as [NewObject]
- Link all Web IDL extended attributes in IDL blocks to their definitions, similar to most other web standards
> Some Web IDL extended attributes improvements

- master/text.html
Fixes https://github.com/w3c/svgwg/issues/271
> Text Layout Algorithm: Fix incorrect attribute/variable names in "Adjust positions: dx, dy"
