master/linking.html
Removed the `_replace` keyword, added note explaining why, and updated
other definitions to harmonize with (and reference to) HTML 5
definitions of browsing contexts.
I left in an issue note, as there remain a few differences between SVG and HTML (e.g., case sensitivity) that I think are reasonable but others may disagree.
=> `a` element target attribute

master/implnote.html
I expanded the F.6.3.1 matrices wrong. These are the correct formulas.
Confirmed by [here](http://fridrich.blogspot.com/2011/06/bounding-box-of-svg-elliptical-arc.html) and [here](http://stackoverflow.com/a/8202677/796832).
```
x = rx*cos(theta)*cos(phi) - ry*sin(theta)*sin(phi) + cx
y = rx*cos(theta)*sin(phi) + ry*sin(theta)*cos(phi) + cy
x = rx*cos(&#952;)*cos(&#966;) - ry*sin(&#952;)*sin(&#966;) + cx
y = rx*cos(&#952;)*sin(&#966;) + ry*sin(&#952;)*cos(&#966;) + cy
```
=> Fix `math-arbitrary-point-on-elliptical-arc` aria/fallback description formulas

tools/publish/processing.js
During the generation of the spec pages that contain the IDL, the attribute
was being removed, causing the index generation code to never see an element
with the attribute present.
=> Take the excludefromidl attribute into account.

master/coords.html, master/definitions-compositing.xml, master/definitions.xml, master/interact.html, master/painting.html, master/render.html, master/struct.html
This pull request consists of two new sections, at least one of which (focus management) **needs discussion & approval by the working group** because it's introducing new normative requirements. Links are to compiled versions of the specs.
Shouldn't be controversial. Gathers up content and implicit behavior into clear definitions. Some links/bookmarks in other specs may be broken by moving the section on display/visibility properties to the rendering chapter from the painting chapter.
Addresses the issues brought up by @richschwer in Issue #50. 
Introduces the following normative requirements (based on usability problems in current implementations of keyboard focus control in SVG):
- User agents SHOULD apply visible focus styles. I've worded it to allow these styles to only be applied …
=> Clarify focus management for SVG & define rendered/non-rendered elements

master/struct.html
Many editorial changes, a few normative ones:
- Move the blue boxes down to be associated with the sections specific to title and desc, respectively (after general rules that apply to both)
- Re-arrange a number of sentences/paragraphs to group together normative text for authors vs user agents
- Clarify rules & add example for matching multi-lingual descriptive text
- SHOULD > MUST for user agent exposing text content to accessibility APIs
- Authors SHOULD NOT, authoring tools MUST NOT include empty title/desc (this causes a mess on the accessibility side)
- Advice for which elements should have title/desc
- Purpose of title/desc on non-rendered content
- Clean up the examples of purpose of title & desc
- Mention aria-labelledby when warning against redundant title content
- User agents …
=> Title & desc re-write

master/pservers.html
Clarifies what 'overflow:visible" means on patterns.
Adds note encouraging implementers to render overflow on patterns as this is what authors expect and is difficult for authors to simulate manually.
=> Note on pattern overflow.

master/changes.html, master/conform.html, master/coords.html, master/embedded.html, master/images/embedded/videofallback.svg, master/images/embedded/videofallbacksizing.svg, master/images/embedded/videotransform.svg, master/linking.html, master/paths.html, master/render.html, master/shapes.html, master/struct.html, master/text.html, master/xhtml1-transitional+edit.dtd
(Ultimately, this commit should not change the meaning of the text.)
Because this is a standard, it is probably best not to employ the rather
informal second person, `you'. This commit removes that usage without
descending into overtly bureaucratic language.
Furthermore, as a matter of practicality or even necessity, some of
the nearby text has also been improved (according to this author);
this includes rewording, re-styling, the removal of typos, and the
fixing of grammar.
=> Copy Editing: Eradicate the usage of informal `you'; clean up surrounding text

master/changes.html, master/pservers.html, master/struct.html
Just a little change to the spec to demonstrate how we will do PRs on the SVG 2 CR draft.
=> Correct SVGUseElementShadowRoot interface definition. Closes #290.

master/changes.html, master/types.html
According to the definition of inheritance in WebIDL. Closes #298.
=> Clarify that SVGElement.className overrides Element.className

master/painting.html
According to CSS 3 Color, `currentColor` is a part of `<color>`, so we don't need to explicitly specify it
r? @nikosandronikos
=> Remove explicit currentColor from <paint>

master/changes.html, master/paths.html
Paths: Remove bearing commands
Bearing commands 'B' and 'b' remain in the SVG Paths spec
https://www.w3.org/TR/svg-paths/#PathDataBearingCommands
but are being removed from svg2-draft.
Resolution:
https://github.com/w3c/svgwg/issues/385#issuecomment-363207475
=> Paths: Remove bearing commands

master/paths.html
Requirement has been removed from SVG2 draft as there are no implementations.
https://github.com/w3c/svgwg/issues/385#issuecomment-363207475
=> Remove path rotation requirement

specs/svg-authoring/index.html
The a element should require an href attribute to be focusable. 
I could be wrong, but I don't think text elements are focusable by default.
Updating non-negative, rather than positive to refer to tabindex values of 0.
=> Revisions to sentence on focusable elements

master/changes.html, master/definitions.xml, master/refs.html, master/types.html
Fixes #60 
Remove definiion of dataset/focus/blur/tabIndex and include mixin from HTML instead.
I've kept the content attribute definition of tabindex until we figure out what to do with the reflecting content attributes that pair with IDL attributes in mixins.
=> Add HTMLOrSVGElement mixn

master/changes.html, master/styling.html
Fixes all the linting issues except text content in an iframe. It looks like according to the HTML spec, fallback content is never allowed. I didn't want to just strip the text out as it is part of the example.
=> Keep the linting minions happy

master/coords.html, master/embedded.html, master/geometry.html, master/interact.html, master/linking.html, master/painting.html, master/pservers.html, master/render.html, master/shapes.html, master/struct.html, master/styling.html, master/text.html, master/types.html
Fixes #417 
I've only touched the main spec and not the various sub specs, as that will take a while.
I included data-dfn-exports (seems to be a typo of using dfn-exports in the spec) to most things. I don't know if this is correct, but it seems if we want to mark things up as definitions then they are thinks that should be useful to export/link to.
=> Add or update dfns for definitions

master/changes.html, master/definitions.xml, master/types.html, specs/animations/master/definitions.xml, specs/markers/master/definitions.xml
Fixes #395  (any additional members should have their own issue)
Supported by Firefox and Edge (upcoming version) as specified. Supported by Chrome and Safari on Element (HTML defines them on HTMLElement so Safari/Chrome have them one level too high)
Tests: https://github.com/w3c/web-platform-tests/pull/10249
=> Add DocumentAndElementEventHandlers

master/definitions.xml
Updated the remaining references for HTML, DOM, and CSSOM.
There are various DOM L2 Views and Style references that I didn't update as they don't exist in either DOM or CSSOM. They need checked to see if they should be removed (AbstractView, CSSPrimitiveValue, DocumentCSS, RGBColor, ViewCSS). None of these interfaces are in Edge, and probably not in other browsers either.
=> Update spec references for HTML, DOM and CSSOM

master/coords.html, master/embedded.html, master/geometry.html, master/interact.html, master/linking.html, master/painting.html, master/pservers.html, master/render.html, master/shapes.html, master/struct.html, master/styling.html, master/text.html, master/types.html
The multi-page versions of the SVG spec have gone from https://svgwg.org/svg2-draft/ . It looks from the linting emails that it was probably due to the missing attribute values (weirdly other xml failures like missing end tags and single quotes don't seem to phase it)
I've fixed those issues and the duplicate IDs in this PR
We should probably make the linter run on the GitHub side so that it warns you instead of giving you a green check mark, if anyone knows how to do that.
=> Fix lint/build issues

master/definitions.xml, master/refs.html, master/struct.html
Some of our links go to places that don't offer any exports. Updating the HTML AAM ones to the h3 which should automatically export. Filed a bug on Filters spec for them to fix the issue in their spec that causes linting issues here.
=> Remove unused defs and fix some linking issues

master/definitions.xml, master/text.html
Fixes #447
The spec redefines white-space, which is defined in CSS Text Level 3 (which is also pointed out in the note). Removing this means the incorrect computed value is removed and makes sure implementers/devs use the CSS version.
Also removed the compat info about Firefox.
=> Remove defintion of white-space

master/definitions.xml
=> Remove unneeded 'shape-outside' definition. Fixes #288.

master/styling.html
The isolation property mentioned in Required properties is defined in defined
in Compositing and Blending Level 1.
fixes #472
=> Fix reference for isolation property

master/coords.html, master/implnote.html, master/pservers.html, master/shapes.html, master/struct.html, master/text.html
I’ve checked for a few common words whether they occur twice in a row, which is a common typo, and fixed these.
=> remove redundant words

master/changes.html, master/text.html
Remove unintended restriction that 'pathLength' only applied to paths and not shapes in regard to 'startOffset'.
Fixes #382.
=> Textpath pathlength

master/types.html
This change:
1. makes it visually look like an example
2. enables IDL crawlers to exclude it.
=> Mark SVGNameList as an example

master/changes.html, master/styling.html
We no longer require clip support in SVG user agents.
CSS Masking has deprecated the clip property in favor of clip-path.
fixes #479
=> Remove requirement for clip property support

master/propidx.html
First part of #82.
I've added the computed value column and removed all properties that link to other specs.
I've an open question about a number of the other ones. They're often defined elsewhere, so feel like they should be removed, but link to parts of the SVG spec. They sometimes just give some historical information about how it has changed since 1.1 that doesn't seem much value can can probably be removed and the information added to the changelog (if not there already). Others Give additional rules about SVG. 1 or 2 give the definition block in SVG and link to a CSS spec (which don't always match). White-space is an example of the latter: https://svgwg.org/svg2-draft/text.html#WhiteSpaceProperty vs https://www.w3.org/TR/css-text-3/#white-space-property I think the computed value …
=> Update property index

master/Overview.html, master/access.html, master/changes.html, master/definitions.xml, master/render.html, master/text.html
The intent is to support z-index in SVG 2.1
resolves #483
=> Defer z-index support from SVG 2

master/text.html
Move ">" symbol of svg element to include width, height, and viewBox attributes.
=> Make "Example of text auto-wrapped" example valid.

master/changes.html, master/paths.html
When values like startOffset are expressed as percentages,
pathLength has no effect. This includes when pathLength is 0.
resolves #383
=> pathLength does not affect percentage calculations

master/text.html
Make the "pre-formatted text" and "Text on a path" xml valid by shifting the ">" of the svg element after the attributes.
This follows a recent similar correction I made to another nearby example.
=> Make examples xml valid.

master/struct.html, tools/publish/processing.js
This is what bikeshed does e.g. in [CSSOM](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-_webkit_cased_attribute). It doesn't remove the flag so that IDL crawlers can also detect it.
=> Use class="extract" to exclude IDL

specs/marker/Overview.bs
The definition is now select( `<compound-selector>` # ).
resolves #498
=> Marker: update <child-selector> syntax

master/propidx.html
text.html already mentions
> The property is now inherited. (Behavior is effectively unchanged.)
propidx.html (which is not normative) now also describes
dominant-baseline as inherited.
dominant-baseline became inherited when its definition moved from
SVG 1.1 to CSS. Confirmed today by CSS WG:
https://github.com/w3c/csswg-drafts/issues/2926
=> Consistently say dominant-baseline is inherited

master/struct.html, tools/publish/processing.js
Reverts commit 63a42e41f0009ef737ab9f58f83e689ed88007ef
Creates the same effect using the build system:
elements with the `edit:excludefromidl="true"` attribute in the source
are given the class "extract" in the build.
Which apparently has an effect in the Reffy system
(for parsing the IDL of different specs),
though I'm not sure exactly what.
See https://github.com/tidoust/reffy/issues/123
=> Revert & replace changes from PR #495

master/definitions.xml, master/paths.html, master/shapes.html
Because we use it to define the equivalent paths of basic shapes.
I've changed the terminology to refer to the segment-completing close path as an _operation_ instead of a _command_, and have added a short sub-section defining it.
I also included a very short note about the proposal for adding it to the path data syntax, in a future version of the specification.
This fixes build problems introduced by PR #398.
@ewilligers can you take a look at the new text I've added & let me know if you think it works to patch over the disconnect.
=> Reintroduce segment-completing closepath as a theoretical concept

master/backward.html, master/color.html, master/concepts.html, master/definitions.xml, master/escript.html, master/extend.html, master/feature.html, master/filters.html, master/fonts.html, master/i18n.html, master/java.html, master/masking.html, master/metadata.html, master/minimize.html, master/paths.html, master/publish.xml, master/script.html, master/shapes.html, master/struct.html, master/svgdtd.html, tools/publish/processing.js
As resolved in the [13 August 2018 teleconference](https://www.w3.org/2018/08/13-svg-minutes.html#resolution01):
> RESOLUTION: If possible, add stub pages to spec for SVG 1.1 chapters that no longer exist, redirecting to correct specs for the content.
So that links to URLs of the form https://www.w3.org/TR/SVG/backward.html won't 404.
Where relevant, the stubs include a very brief description of what happened to the content, with links to its current location (e.g., another chapter or a CSS spec). There are also links back to the SVG11 TR version of the chapter, and to the main SVG2 Overview page.
To include these files in the final build, without messing up building the actual spec, they are included as "resource" files in publish.xml. This means that they are copied as-is to the final …
=>  Add stub files for removed chapters/appendices

master/text.html
Attempt to address I18N comments in #263, #262, and #259.
=> Clarify character related definitions. #263, #262, #259.

master/animate.html, master/changes.html, master/conform.html, master/definitions.xml, master/embedded.html, master/interact.html, master/intro.html, master/linking.html, master/refs.html, master/render.html, master/struct.html, master/styling.html, master/text.html, master/types.html
Update all internal links to [HTML] which were linking to HTML 5.1 in the refs (with the wrong bibliographic reference). Actual [HTML51] was not found.
=> Change from HTML 5.1 to HTML LS, #514

master/changes.html, master/conform.html, master/refs.html
As this is an optional feature, informative references are fine. CSS Color 4 defines how to use ICC profiles in CSS, while the ICC ref covers the actual ICC profile format and meaning.
=> Fix #532 with informative refs to ICC  & ICC support in css-color-4

master/changes.html, master/painting.html, master/propidx.html
Addresses (but does not close) #545. 
Note:
The interpretation of numerical values for miter-clip and arcs joins hasn't been changed.
In these cases, values less than 1 won't have the same rendering as 1.
=> Allow any non-negative number for stroke-miterlimit

master/shapes.html
A computed radius value of zero disables rendering of the circle element.
This restores a sentence that was accidentally removed.
fixes #560
=> <circle> with r=0 has rendering disabled

master/changes.html, master/interact.html, master/propidx.html
Add the keyword 'auto' as the initial value for pointer-events.
Browsers already support 'auto' as the initial value.
resolves #574
=> [interactivity] pointer-events auto

master/text.html
For consistency with browsers and CSS,
the initial value of inline-size is auto
https://drafts.csswg.org/css-logical/#dimension-properties
=> inline-size has initial value auto

master/changes.html, master/interact.html
…requirement to scan raster image pixels. #322
=> CSS pointer-events on (raster) images does not require scanning pixels

master/propidx.html, master/pservers.html
Like other *-opacity properties, the computed value for stop-opacity is clamped to [0,1].
stop-opacity is currently the only one of the following properties not to have this clamping mentioned in "Computed value:" wording.
- [opacity](https://drafts.csswg.org/css-color/#propdef-opacity)
- [flood-opacity](https://drafts.fxtf.org/filter-effects/#FloodOpacityProperty)
- [fill-opacity](https://drafts.fxtf.org/fill-stroke/#fill-opacity) (also in [SVG2](https://svgwg.org/svg2-draft/painting.html#FillOpacity))
- [stroke-opacity](https://drafts.fxtf.org/fill-stroke/#stroke-opacity) (also in [SVG2](https://svgwg.org/svg2-draft/painting.html#StrokeOpacity))
- stop-opacity (in [SVG2](https://svgwg.org/svg2-draft/pservers.html#StopOpacityProperty))
=> stop-opacity computed value is clamped

master/styling.html
Fixes the priority of the presentation attributes in the CSS cascade (reverting it to the SVG 1.1 definition, which matches the browser reality).
=> Fixes #596

master/propidx.html
stroke-dasharray percentages are relative to the normalized diagonal
of the viewport.
=> Property Index: explain stroke-dasharray %

master/Overview.html
- Move @Tavmjong back to the active editors list (he really shouldn't have ever been removed)
- Move @boggydigital and @dstorey to the former editors list (unless one of you is going to be reassigned back to the WG when it reconvenes in the new year…?)
Also: @satakagi, do you expect to do any active work on the spec this year?
=> Update current/former editors list

master/refs.html
In the [References](https://svgwg.org/svg2-draft/refs.html) appendix, the following are now links:
[css-cascade-4]
[css-scoping-1]
[SMIL]
[web-animations-1]
[css-color-4]
[css-shapes-2]
[svg-animation]
resolves #632
=> [References] Fix missing links

master/coords.html
As discussed in https://github.com/w3c/svgwg/issues/406#issuecomment-411846579
(except substituting
local coordinate → user coordinate
because of other changes)
Closes #406.
=> Clarify intro text re percentage units

master/definitions.xml, master/geometry.html, master/painting.html, master/shapes.html, master/struct.html, master/types.html
But many values are <a>invalid</a> and must be <a>ignored</a>!
Changes the prose describing non-negative value constraints
to use the CSS 3 terms.
"invalid" is linked to the existing definition of "invalid value"
in the types chapter.
"ignored" links directly to the CSS Syntax definition
(ED version for now; the published CR is out of date.)
Closes #639 and tidies up changes made in #637.
=> No value is illegal

master/changes.html, master/coords.html, master/definitions.xml, master/types.html
As resolved in https://github.com/w3c/svgwg/issues/547#issuecomment-424105119
> RESOLUTION: Setting a enum-like DOM property to a value
> that doesn't represent a valid attribute value
> should throw a TypeError
This affects the setter algorithm for
SVGAnimatedEnumeration
and for SVGPreserveAspectRatio.
Clarifying changes made to:
-  the note regarding reserializing an SVGAnimatedEnumeration,
- the general statement about
silently ignoring invalid values.
Closes #547.
=> Enum-like DOM properties throw TypeErrors on setting to unknown values

master/paths.html
Period/Full-stop is U+002E, not U+0046 (which is a capital F).
For issue #649.
=> Fix for #649. Incorrect Unicode code point reference

master/mimereg.html
Set the contact point (which has to be an email address) to the public SVG list; and also point to a GitHub issue which is a better place for any comments.
Oh and some trailing whitespace normalization.
Fixes #655
=> close #655

master/intro.html
The suggested text I offered in bug #199 seemed to be acceptable to people,. So I have created a PR based on that. The text here has been slightly modified from the original.
Bug #199 has been marked as deferred to 2.1. But I think it would be a good idea to include this in the first release of SVG 2.
=> Added paragraph about Tiny 1.2 being deprecated (bug #199)

master/conform.html
Added as an informative note in the [conformance section on SVG servers](https://svgwg.org/svg2-draft/conform.html#ConformingSVGServers).
Closes #701
=> Expanded note on server configuration and SVGZ

master/Overview.html, master/changes.html, master/definitions.xml, master/interact.html, master/linking.html, master/struct.html, master/types.html
Closes #56.
Adds a note about the legacy spec, in the context of currentScale and currentTranslate.
Remaining ambiguities about these IDL properties are covered in #360.
An inline issue is included.
=> Remove zoomAndPan attribute

master/changes.html, master/definitions.xml, master/struct.html
This fixes https://github.com/w3c/svgwg/issues/726
=> Add 'autofocus' core attribute

master/text.html, master/types.html
Default value '{}' is specified for optional
'DOMPointInit' and 'SVGBoundingBoxOptions'
arguments to methods of
- SVGGeometryElement
- SVGGraphicsElement
- SVGTextContentElement
resolves #727
=> Default value '{}' is specified for optional dict

master/propidx.html, master/pservers.html
We previously defined the stop-color syntax as
`currentColor | <color> <icccolor>`
which would have suggested that `black icc-color(name)` is
a valid stop-color but `black` is not.
=> Link to definition of color for stop-color syntax

master/changes.html, master/definitions.xml
=> Remove onfocusin and onfocusout event attributes.

master/style/svg.css, tools/publish/processing.js
The middle dot characters got turned into periods at one point.
Also make the text a bit smaller so that it fits on one line.
=> tweak styling of the header links

specs/svg-native/index.bs
This reorganizes the SVG Native spec to match SVG 2. I don't believe there are any (meaningful) behavior changes.
While doing this, I also included all the resolutions the SVG WG has made. A link to each resolution is included in a comment in the source.
This should catch the SVG Native spec up with current discussion.
=> Rebase the SVG Native spec on top of SVG 2

.gitignore
- We don't need to mention subdirectories of 'build', since we're
ignoring that already.
- Ignoring all files with the name 'issue-state.txt' instead of
having to manually add them each time we add one.
- Ignore *.swp files.
=> Make the .gitignore patterns more robust, and simpler

master/definitions.xml, specs/animations/master/Overview.html
AbstractView is an obsolete term from DOM2\[0\]. The Gecko implementation
of TimeEvent uses WindowProxy and Window instead\[1\], so this change
aligns the spec with that.
Fixes https://github.com/w3c/svgwg/issues/775
[0]: https://www.w3.org/TR/DOM-Level-2-Views/views.html#Views-AbstractView
[1]: https://github.com/mozilla/gecko-dev/blob/cfd1cc461f1efe0d66c2fdc17c024a203d5a2fd8/dom/webidl/TimeEvent.webidl#L17
=> Replace AbstractView with WindowProxy/Window

specs/color/Overview.bs
The plain `<a>` wrapping was making a nested link with the `'` linking.
/cc @tabatkins in case there was a better wrapping to use here
=> [color] Double link wraps in Bikeshed

specs/paths/master/Overview.html
=> [svg-paths] Add default value {} to getPathData argument

master/struct.html
The Constructor extended attribute has been removed from Web IDL.
=> Use constructor operation for ShadowAnimation

master/types.html, specs/animations/master/Overview.html
These were missed in https://github.com/w3c/svgwg/pull/387 and should be
the last cases of missing [Exposed] in SVG.
=> Add remaining [Exposed=Window] where still missing

master/struct.html
As an interface mixin, Animatable can't be used as a type per Web IDL:
https://heycam.github.io/webidl/#idl-types
Expand it to (Element or CSSPseudoElement), the two interfaces that include Animatable.
=> Avoid the use of Animatable as a Web IDL type

master/coords.html, master/struct.html
This is required by Web IDL, but because DOMMatrix2DInit is defined in
another spec wasn't noticed until all spec IDL was validated together.
See https://github.com/w3c/webidl2.js/issues/407 for a discussion about
the underlying validation problem.
=> Add default value {} for optional DOMMatrix2DInit arguments

master/styling.html
This PR is meant to mirror https://github.com/whatwg/html/pull/7779 by giving SVGStyleElement a `disabled` IDL attribute that does not mirror any content attribute. Furthermore, this PR is so small because I believe just adding the attribute is enough to piggy-back on the semantics in the WHATWG PR above, given the [following text](https://svgwg.org/svg2-draft/styling.html#:~:text=The%20semantics%20and%20processing%20of%20a%20%E2%80%98style%E2%80%99%20and%20its%20attributes%20must%20be%20the%20same%20as%20is%20defined%20for%20the%20HTML%20%E2%80%98style%E2%80%99%20element.) in the SVG styling spec:
> The semantics and processing of a ‘[style](https://svgwg.org/svg2-draft/styling.html#StyleElement)’ and its attributes must be the same as is defined for the [HTML ‘style’ …
=> Add SVGStyleElement#disabled attribute

master/definitions.xml, master/interact.html, master/types.html
This mixin will be removed from HTML, and the 3 event handler attributes
will be added to GlobalEventHandlers instead:
https://github.com/whatwg/html/pull/8096
https://github.com/web-platform-tests/wpt/pull/36398
=> Stop using the DocumentAndElementEventHandlers interface mixin

master/struct.html
Assigning an attacker controlled string to `SVGUseElement.href` causes XSS due to data: URLs. This also led to a [bypass of Trusted Types](https://github.com/w3c/trusted-types/issues/357) in Blink.
Additionally, data: URLs can only trigger script execution in script loaders such as HTMLScriptElement.src or [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import). However, SVGUseElement is an exception to this, which also caused a [bypass](https://bugs.chromium.org/p/chromium/issues/detail?id=1306450#c10) in the Sanitizer API. We believe that this also led to several other bugs in sanitizers and linters missing a check for this special case.
Since Webkit does not support data: URLs in SVGUseElement, Blink is planning to remove support for it. And …
=> Remove support for data: URL in SVGUseElement

master/text.html
Cf. w3c/fxtf-drafts#523 and https://github.com/w3c/csswg-drafts/pull/9132 for why it may be required.
=> Add missing whitespace before combinator in value definition

master/paths.html
Hello SVG WG.
I'm currently implementing an SVG Path parser and it appears that the SVG2 path grammar is a little inconsistent with SVG 1.1 and with other current implementations (AFAIK those from web browsers).
Many details have been discussed in issue #752 (mostly point 1 and 2 raised by @dalboris)
This PR is a proposed fix for the missing trailing white spaces after commands and at end of path. The intent is to prevent a breaking change to the SVG Path grammar. If the SVG WG think this breaking change should be kept, so it should be clearly stated (exactly like the warn done for numbers with trailing dot). If so, I would be glad to update this PR accordingly.
+@dalboris
=> Fix missing trailing wsp after path commands

master/types.html
This PR upstreams the trusted types integration with SVGAnimatedString. See https://www.w3.org/TR/trusted-types/#integration-with-svg
=> Upstream Trusted Types integration with SVGAnimatedString

master/shapes.html
=> Correct sweep-flag in circle/ellipse equivalent paths

master/linking.html
This corrects the link from .rel to .relList.
=> Correct link for SVGAElement.relList

master/implnote.html
Equation 6.1 on [this page](https://www.w3.org/TR/SVG/implnote.html#ArcCorrectionOutOfRangeRadii) has two identical lines, both showing $r_y \leftarrow |r_y|$. The two lines should be different, where the first would be changed to $r_x \leftarrow |r_x|$. It's a small inaccuracy that doesn't really make the page any harder to understand, but it's still probably worth fixing 🙂
=> Fix equation 6.1 in implnote.html

master/styling.html
`text-space-collapse` was renamed `white-space-collapse` in 2023: https://github.com/w3c/csswg-drafts/issues/8273
=> Use white-space-collapse property instead of old name for it

master/linking.html
This was only implemented by Firefox, where it has now been removed (https://bugzilla.mozilla.org/show_bug.cgi?id=1880689).
Discussion in GH-931 indicated that this attribute is desired to be removed from the spec.
Closes GH-931.
=> Remove SVGAElement.text attribute

master/styling.html
The property itself has already been removed.
=> Remove glyph-orientation-horizontal presentation attribute

specs/animations/master/Overview.html
See  https://github.com/whatwg/dom/pull/417 and https://github.com/whatwg/html/pull/2410
This fix landed in Firefox as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1345044 and already has a test in https://wpt.fyi/results/svg/idlharness.window.html?label=experimental&label=master&aligned
=> Default some arguments of initTimeEvent

master/text.html
No name change for `d` attribute. See ANNOTATION 1:
https://www.w3.org/TR/SVG/paths.html#PathElement
=> textPath example: Replace `path` attribute with `d`

master/painting.html, specs/markers/master/Overview.html
Firefox is implementing the value auto-start-reverse as an IDL. 
The context for the decision was made in #424
where only 
* `SVG_LENGTHTYPE_*` 
* `SVG_ANGLETYPE_*` constants
* enumeration for new CSS units 
**should NOT** be extended. 
but this is not the case for `SVG_MARKER_ORIENT_*`. 
Hence the extension with this PR to align with Firefox.
FIXME: `SVGFECompositeElement` will be done in a separate PR.
=> Fix #993: Add SVG_MARKER_ORIENT_AUTO_START_REVERSE to the IDL.

master/struct.html
Required by Web IDL. This had been fixed in #844 but dropped by mistake when #783 was merged.
=> (Re-)Add default value for optional `DOMMatrix2DInit` args

master/struct.html
Re-apply #840 to the `main` branch. As an interface mixin, `Animatable` can't be used as a type per Web IDL.
(I had missed that second update in #1010)
=> Avoid the use of `Animatable` in `ShadowAnimation` constructor
